// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcgXVz5YoUF89cNVIIdhMpGxw7mhCrtrQ',
    appId: '1:663414398790:web:7bd3d53dec415a4d180f47',
    messagingSenderId: '663414398790',
    projectId: 'smartbez',
    authDomain: 'smartbez.firebaseapp.com',
    databaseURL: 'https://smartbez-default-rtdb.firebaseio.com',
    measurementId: 'G-3XL7NYF86E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-fzIkOxhofGGktXukUE7IpldHuvMxRXs',
    appId: '1:663414398790:android:cf842dfb600d829e180f47',
    messagingSenderId: '663414398790',
    projectId: 'smartbez',
    databaseURL: 'https://smartbez-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALytjza7WbCeXCuE3Gpks-TcjNpZc03FY',
    appId: '1:663414398790:ios:a36b543f5941b115180f47',
    messagingSenderId: '663414398790',
    projectId: 'smartbez',
    databaseURL: 'https://smartbez-default-rtdb.firebaseio.com',
    storageBucket: 'smartbez.firebasestorage.app',
    iosClientId: '663414398790-c4grc3385fbar8ddttrhk4sp3t4u2ehe.apps.googleusercontent.com',
    iosBundleId: 'com.example.swipify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALytjza7WbCeXCuE3Gpks-TcjNpZc03FY',
    appId: '1:663414398790:ios:a36b543f5941b115180f47',
    messagingSenderId: '663414398790',
    projectId: 'smartbez',
    databaseURL: 'https://smartbez-default-rtdb.firebaseio.com',
    storageBucket: 'smartbez.firebasestorage.app',
    iosClientId: '663414398790-c4grc3385fbar8ddttrhk4sp3t4u2ehe.apps.googleusercontent.com',
    iosBundleId: 'com.example.swipify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcgXVz5YoUF89cNVIIdhMpGxw7mhCrtrQ',
    appId: '1:663414398790:web:f73aaafc26f8d87e180f47',
    messagingSenderId: '663414398790',
    projectId: 'smartbez',
    authDomain: 'smartbez.firebaseapp.com',
    databaseURL: 'https://smartbez-default-rtdb.firebaseio.com',
    storageBucket: 'smartbez.firebasestorage.app',
    measurementId: 'G-J25RK34GWZ',
  );
}
